### ISSUE TITLE
Ember 2.12 incompatibility?

### ISSUE THREAD

**Issue by jdurand** [ember-cli/ember-load-initializers#40] opened 2017-03-21 17:33 UTC
Running my tests suite with Ember 2.12.0 produces the following warning:

<code>DEPRECATION: Addon files were detected in `[...]/node_modules/ember-load-initializers/addon`, but no JavaScript preprocessors were found for `ember-load-initializers`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-load-initializers`'s `package.json`.</code>

... even though `ember-cli-babel` is set as a dependency in `package.json` for `ember-load-initializers`.

Then, my test suite fails with:

`not ok 1 PhantomJS 2.1 - Global error: SyntaxError: Use of reserved word 'export' at http://localhost:7357/assets/test-support.js, line 14642`

Locking Ember to 2.11.0 fixes the issue.

My `package.json`:

```
{
  [...]
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-basic-dropdown": ">= 0.16.0-beta.6",
    "ember-cli": "^2.11.0",
    "ember-cli-app-version": "~2.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-dotenv": "1.2.0",
    "ember-cli-fastclick": "1.2.0",
    "ember-cli-gzip": "^1.1.3",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-loading-slider": "1.3.0",
    "ember-cli-mirage": "^0.2.1",
    "ember-cli-mocha": "^0.10.4",
    "ember-cli-moment-shim": "2.0.0",
    "ember-cli-rails-addon": "~0.8.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "~5.4.0",
    "ember-cli-sentry": "2.4.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-cli-underscore": "0.0.3",
    "ember-data": "^2.11.0",
    "ember-export-application-global": "^1.0.5",
    "ember-font-awesome": "2.1.1",
    "ember-i18n": "^4.2.2",
    "ember-i18n-iso-countries": "1.1.0",
    "ember-intl-tel-input": "^1.2.0",
    "ember-load-initializers": "^0.6.3",
    "ember-moment": "^7.0.0-beta",
    "ember-percy": "1.2.5",
    "ember-pikaday": "2.1.0",
    "ember-power-select": "^1.4.4",
    "ember-resolver": "^2.0.3",
    "ember-route-action-helper": "^2.0.0",
    "ember-social-share": "git://github.com/jdurand/ember-social-share.git",
    "ember-wormhole": "^0.4.0",
    "loader.js": "^4.0.1",
    "torii": "git://github.com/jdurand/torii.git"
  }
}
```

Any hints on where to look at?

**Comment by rwjblue** [comment] 2017-03-21 18:31
> DEPRECATION: Addon files were detected in [...]/node_modules/ember-load-initializers/addon, but no JavaScript preprocessors were found for ember-load-initializers. Please make sure to add a preprocessor (most likely ember-cli-babel) to in dependencies (NOT devDependencies) in ember-load-initializers's package.json.

This warning was fixed in https://github.com/ember-cli/ember-load-initializers/pull/37, and released in 0.6.3.

> not ok 1 PhantomJS 2.1 - Global error: SyntaxError: Use of reserved word 'export' at http://localhost:7357/assets/test-support.js, line 14642

I doubt that this issue is caused by ember-load-initializers.  The best thing to do would be to inspect `dist/assets/test-support.js` at line 14642 and see what addon that is from.  Most likely they are not properly transpiling in a custom `treeForAddon` hook.

**Comment by rwjblue** [comment] 2017-03-21 18:32
I'm going to close this for now, as I do not believe this is an issue here.  Please feel free to continue the conversation as you dig deeper into your various addons...

**Closed by rwjblue** 2017-03-21 18:32 UTC

**Comment by bracke** [comment] 2017-06-23 13:43
I have the same problem with the addon 'ember-ted-select' (2.2.2) and Ember 2.13.1.
Downgrading to Ember 2.11.0 fixed it.

The error message:

DEPRECATION: Addon files were detected in `/node_modules/ember-ted-select/addon`, but no JavaScript preprocessors were found for `ember-ted-select`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-ted-select`'s `package.json`.

Ember-ted-select's package.json already contains '"ember-cli-babel": "^5.1.7"'.
Se https://github.com/tedconf/ember-ted-select/blob/master/package.json
